### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by letonchanh** [ngorogiannis/cyclist#5]
Hello,

I cannot compile the current source code with the instruction at 

    http://www.cyclist-prover.org/installation

The error I encountered is 

    File "src/mparser/mParser_Sig.mli", line 47, characters 34-41:
    Error: Unbound module Bytes

So I tried to use the newer version 4.02.1 of OCaml, while the version of the dependent libraries is still the same. However, now there is an error when linking 

    collect2: error: ld returned 1 exit status
    File "caml_startup", line 1:
    Error: Error during linking
    Command exited with code 2.
    Compilation unsuccessful after building 123 targets (5 cached) in 00:00:14.
    make: *** [src/generic/checkproof.native] Error 10

The error also occurs with the newest version of the dependent libraries.
Could you please provide instruction on how to compile the current source code?
Thank you very much.

**Comment by ngorogiannis** [comment]
Hi, thanks for reporting this. Indeed you need OCaml 4.02.x as a minimum -- I will update the pages.

Try `make clean ; make` and let me know if that works.

**Comment by letonchanh** [comment]
Hi,

Thanks for your reply. 

Actually, I am using OCaml 4.02.1 but it does not work because of a linking error.
You can find the error message at http://pastebin.com/VLq6KBmU.

**Comment by ngorogiannis** [comment]
Right, did you try `make clean ; make`?

If you have, did you upgrade g++ after compiling Spot? What is the version of g++ and of libstc++?

**Comment by reubenrowe** [comment]
This could be because line 53 of myocamlbuild.ml is commented out.

     A"-cclib"; A"-Wl,--no-as-needed";

At some point when updating to the new version of Spot, Daniele 
commented this out because he didn't need it for his Mac build. However, 
I have always kept it in for my Linux build because otherwise I got 
linking errors.

Reuben

**Comment by letonchanh** [comment]
@reubenrowe It's working now. Thanks a lot.
