### ISSUE TITLE
sl_satcheck is broken

### ISSUE THREAD

**Issue by letonchanh** [ngorogiannis/cyclist#6]
Hi,

I am playing around with sl_satcheck and encountered the below error

./sl_satcheck.native -D benchmarks/slsat/syn/test1.defs

Fatal error: exception File "src/seplog/sl_indrule.ml", line 17, characters 2-8: Assertion failed

**Comment by reubenrowe** [comment]
Hi Ton,

I will look into this.

Can you give me the SHA of the commit that you are building from?

Thanks,

Reuben

**Comment by letonchanh** [comment]
Hi Reuben,

I tried the latest commit  1a1c17f.

Thanks,

Chanh

**Comment by reubenrowe** [comment]
The inductive definitions need every variable in the body of a production which is not a parameter to be existential variables - there is an assertion in the code that checks this.

I think these definitions were automatically generated using the perl scripts in the benchmark subdirectory. We probably need to change these scripts to make sure they generate definitions with variables correctly quantified, but I'm leaving this for later.

I have changed the .defs files, so they can be by for the sl_satcheck binary.

**Comment by letonchanh** [comment]
Thank you for letting me know that.
